# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False, verbose_name='\u7f16\u53f7')),
                ('aname', models.CharField(max_length=30, verbose_name='\u7ba1\u7406\u5458\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='\u4e66\u7c4d\u7f16\u53f7')),
                ('bname', models.CharField(max_length=30, verbose_name='\u56fe\u4e66\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20, unique=True, verbose_name='\u7c7b\u578b')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='\u7f16\u53f7')),
                ('uname', models.CharField(max_length=30, verbose_name='\u7528\u6237')),
                ('upwd', models.CharField(max_length=20, verbose_name='\u5bc6\u7801')),
                ('created', models.DateField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Userborrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u501f\u4e66\u65f6\u95f4')),
                ('bname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookManage.Book', verbose_name='\u4e66\u7c4d\u540d\u79f0')),
                ('unmae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookManage.User', verbose_name='\u7528\u6237id')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='btype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookManage.BookType', verbose_name='\u4e66\u7c4d\u7c7b\u578b'),
        ),
    ]
